### ISSUE TITLE
Feedback for "Developer PaaS Scenario"

### ISSUE THREAD

**Issue by axel-schroeder** [SAP-docs/btp-ui-theme-designer#3]
https://help.sap.com/docs/btp/ui-theme-designer/developer-paas-scenario

In the first sentence, this page states "SAP BTP Portal"
I'm not aware of such a product. What is meant here? Could you provide a link?

**Comment by CHoefkens** [comment]
Hi. BTP stands for Business Technology Platform. There's a link to the documentation for this in the breadcrumb in the black header bar on the Developer-PAAS-Scenario page.  I'll also update the page with the name in full. Thanks for your comment :-)

**Comment by CHoefkens** [comment]
Thanks Axel. I will make the changes as we discussed in Teams.  Regards, Celeste
